### ISSUE TITLE
Segmentation fault at parser/mpOprtIndex.cpp:61

### ISSUE THREAD

**Issue by nasailja** [beltoforion/muparserx#56]
Same program as in https://github.com/beltoforion/muparserx/issues/55, `0M[,1][0/1M[0M]M]` causes a segmentation fault, found with afl:
```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x00000073656e6f08
0x00000073656e6f08 in ?? ()
(gdb) up
Cannot access memory at address 0x73656e6f08
#1  0x00000001000d2c4b in mup::OprtIndex::Eval (this=0x100206a10, ret=@0x1002053d8, a_pArg=0x1002053e0, a_iArgc=2122560) at parser/mpOprtIndex.cpp:61
61	            int rows = a_pArg[-1]->GetRows();
(gdb) 
#2  0x000000010002051b in mup::ParserXBase::ParseFromRPN (this=0x7fff5fbff7a0) at parser/mpParserBase.cpp:1090
1090	          pIdxOprt->Eval(val, &idx, nArgs);
(gdb) 
#3  0x00000001000013f0 in main () at muparserx.cpp:17
17			double result = parser.Eval().GetFloat();
```

**Comment by beltoforion** [comment]
Fixed in Version 4.0.1
